schema_version: 20180708
name: pythonfn
version: 0.0.76
runtime: python
entrypoint: python3 func.py
format: http-stream
memory: 256
triggers:
- name: pythonfn-trigger
  type: http
  source: /pythonfn-trigger
